---   
- name: Create users and setup SSH
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
  loop: "{{ users }}"
  become: true

- name: Create home directory and .ssh folder
  ansible.builtin.file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    mode: '0700'
  loop: "{{ users }}"
  become: true

- name: Generate SSH key pair
  ansible.builtin.openssh_keypair:
    path: "/home/islam/.ssh/id_rsa"
  delegate_to: localhost
  become: true

- name: Create authorized_keys file
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/home/islam/.ssh/id_rsa.pub') }}"
  loop: "{{ users }}"
  become: true

- name: Set permissions for authorized_keys file
  ansible.builtin.file:
    path: "/home/{{ item }}/.ssh/authorized_keys"
    mode: '0600'
  loop: "{{ users }}"
  become: true

